import { ValidationService, escapeHTML } from "./utils.js";

export const generateSVG = (d) => {
    if (!d || !d.lines || d.lines.length === 0) return "";
    let p = "";
    d.lines.forEach((l) => {
        if (l.length < 2) return;
        let s = `M ${l[0].x} ${l[0].y}`;
        for (let i = 1; i < l.length; i++) s += ` L ${l[i].x} ${l[i].y}`;
        p += `<path d="${s}" stroke="#2563EB" stroke-width="3" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`;
    });
    return `<svg width="100%" height="100%" viewBox="0 0 350 250" preserveAspectRatio="xMidYMid meet">${p}</svg>`;
};

export const generateReportHTML = (c, prods, dt) => {
    const dObj = new Date(dt), fD = dObj.toLocaleDateString('fr-FR'), fT = dObj.toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit' });
    const css = `@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');@page{margin:15mm}body{font-family:'Inter',sans-serif;max-width:1000px;margin:0 auto;padding:20px;color:#1e293b;line-height:1.4}.header{display:flex;justify-content:space-between;border-bottom:3px solid #2563EB;padding-bottom:20px;margin-bottom:30px}.client-box{background:#f8fafc;padding:20px;border-radius:8px;flex:1;margin-right:20px;border:1px solid #e2e8f0}.meta-box{flex:0 0 300px;text-align:right}.stat-badge{display:inline-block;padding:5px 12px;border-radius:20px;font-weight:bold;font-size:0.9em;margin-bottom:5px}.product-card{border:1px solid #cbd5e1;border-radius:8px;margin-bottom:20px;overflow:hidden;page-break-inside:avoid;box-shadow:0 2px 4px rgba(0,0,0,0.05)}.product-header{background:#f1f5f9;padding:12px 20px;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #cbd5e1;font-weight:700;color:#334155}.product-body{display:grid;grid-template-columns:60% 40%}.specs{padding:15px;font-size:0.9em}.visuals{padding:15px;background:#fcfcfc;border-left:1px solid #e2e8f0;display:flex;flex-direction:column;align-items:center;justify-content:center}table.spec-table{width:100%;border-collapse:collapse}table.spec-table td{padding:4px 0;vertical-align:top}.label{color:#64748b;font-weight:600;width:140px}.value{color:#0f172a;font-weight:500}.drawing-container{border:1px dashed #cbd5e1;width:100%;height:160px;display:flex;align-items:center;justify-content:center;margin-bottom:10px;border-radius:4px}.photo-row{display:flex;gap:5px;flex-wrap:wrap;justify-content:center}.photo-img{width:80px;height:80px;object-fit:cover;border-radius:4px;border:1px solid #eee}.alert-text{color:#d97706;font-weight:bold}.notes-box{margin-top:10px;padding:10px;background:#fffbeb;border:1px solid #fcd34d;border-radius:4px;color:#92400e;font-style:italic}.final-client-box{background:#fffbeb;padding:15px;border:1px solid #fcd34d;border-radius:8px;margin-bottom:30px}@media print{body{padding:0;margin:0}}`;
    let bS = '', bT = '';
    if (c.typeContrat === 'FOURNITURE_ET_POSE') { bS = '#dcfce7;color:#166534'; bT = 'FOURNITURE ET POSE' } else if (c.typeContrat === 'SOUS_TRAITANCE') { bS = '#fef3c7;color:#92400e'; bT = 'SOUS-TRAITANCE' } else { bS = '#dbeafe;color:#1e40af'; bT = 'FOURNITURE SEULE' }
    let h = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Relevé ${escapeHTML(c.client)}</title><style>${css}</style></head><body onload="window.print()"><div class="header"><div class="client-box"><h1 style="margin:0 0 10px 0;color:#2563EB;">${escapeHTML(c.client)}</h1><div>📍 ${escapeHTML(c.adresse)}</div><div>📞 ${escapeHTML(c.telephone)} ${c.email ? ` • ✉️ ${escapeHTML(c.email)}` : ''}</div></div><div class="meta-box"><div class="stat-badge" style="background:${bS}">${bT}</div><br><strong>Date:</strong> ${fD} à ${fT}<br><strong>Produits:</strong> ${prods.reduce((a, b) => a + (b.quantity || 1), 0)}<br></div></div>${c.typeContrat === 'SOUS_TRAITANCE' ? `<div class="final-client-box"><strong>👷 CLIENT FINAL (CHANTIER) :</strong> ${escapeHTML(c.clientFinal)} - ${escapeHTML(c.adresseFinale)}</div>` : ''}`;
    prods.forEach(p => {
        let r = ''; const add = (l, v) => { if (v !== undefined && v !== null && v !== false && v !== '') r += `<tr><td class="label">${l}</td><td class="value">${v === true ? 'OUI' : v}</td></tr>` };
        if (p.room) add('Localisation', `<strong>${escapeHTML(p.room)}</strong>`); add('Quantité', `<strong>x ${p.quantity || 1}</strong>`);
        let dim = `<strong>L ${p.largeurMm} x H ${p.hauteurMm} mm</strong>`; if (p.monobloc && p.coffreADeduireMm && p.hauteurMm) dim += `<br><span style="font-size:0.9em;color:#64748b">Passage = <strong>${p.hauteurMm - p.coffreADeduireMm} mm</strong> (Coffre ${p.coffreADeduireMm})</span>`; add('Dimensions', dim);
        if (ValidationService.isMeasureSuspicious(p.largeurMm, p.monobloc) || ValidationService.isMeasureSuspicious(p.hauteurMm, p.monobloc)) r += `<tr><td class="label">⚠️ Attention</td><td class="value alert-text">Cote < 300mm</td></tr>`;
        if (['FENETRE', 'PORTE_FENETRE', 'BAIE_COULISSANTE', 'PORTE_ENTREE', 'PORTE_SERVICE'].includes(p.type)) {
            add('Matière', p.matiere); add('Profil', `${p.profil} ${p.profil === 'ISO' ? `(${p.isoMm}mm)` : ''}`); add('Couleur', `${p.couleur} ${escapeHTML(p.couleurAutre || '')}`);
            if (p.vitrageFlags) { const v = p.vitrageFlags, va = []; if (v.standard) va.push('4/20/4'); if (v.g200) va.push('G200'); if (v.feuillete1f) va.push('Feuilleté (1F)'); if (v.feuillete2f) va.push('Feuilleté (2F)'); if (va.length) add('Vitrage', va.join(', ')) }
            if (p.type === 'FENETRE' || p.type === 'PORTE_FENETRE') { add('Oscillo-Battant', p.oscilloBattant); add('Grille Vent.', p.grilleVentilation); if (p.poigneeHauteur === 'AUTRE' && p.poigneeHauteurMm) add('Hauteur Poignée', `${p.poigneeHauteurMm} mm`); add('Poignée Clé', p.poigneeCle); add('Ouv. Ext.', p.ouvertureExterieure); if (p.type === 'FENETRE' && p.pieceAppuiDescription) add('Pièce Appui', p.pieceAppuiDescription); if (p.type === 'PORTE_FENETRE') { add('Soubassement', p.soubassement ? `${p.soubassementHauteurMm}mm` : false); add('Serrure', p.serrure); add('Seuil PMR', p.seuilPMR); } }
            if (p.type === 'PORTE_ENTREE') { add('Remplissage', p.remplissage === 'PANNEAU_DECORATIF_ALU' ? 'Panneau Déco Alu' : p.remplissage); add('Seuil PMR', 'OUI'); if (p.tierceImposte) add('Tierce/Imposte', 'OUI'); if (p.tierce) add('Tierce', `Passage: ${p.cotePassageMm}mm`); add('Ouv. Ext.', p.ouvertureExterieure) }
            if (p.type === 'PORTE_SERVICE') add('Seuil PMR', 'OUI');
        }
        if (p.type === 'VOLET_ROULANT') { add('Couleur', `${p.couleur} ${escapeHTML(p.couleurAutre || '')}`); add('Manoeuvre', p.manoeuvre); if (p.sortieCable) add('Sortie Câble', p.sortieCable); if (p.manoeuvre !== 'FILAIRE' && p.boxDomotique) add('Box Domo', 'OUI'); if (p.coupleMoteur) add('Couple', `${p.coupleMoteur}Nm`); if (p.pose) add('Pose', p.pose); if (p.monobloc) add('Monobloc', `OUI (Coffre: ${p.coffreADeduireMm}mm)`); if (p.lieAProduitId) add('Lié à', `#${prods.find(x => x.id === p.lieAProduitId)?.index || '?'}`) }
        if (p.type === 'AUTRE') add('Description', escapeHTML(p.description));
        const dr = p.dessin && p.dessin.lines.length > 0 ? `<div class="drawing-container">${generateSVG(p.dessin)}</div>` : '', im = p.photos && p.photos.length > 0 ? `<div class="photo-row">${p.photos.map(s => `<img src="${s}" class="photo-img"/>`).join('')}</div>` : '', nt = p.notes ? `<div class="notes-box">Note: ${escapeHTML(p.notes)}</div>` : '';
        h += `<div class="product-card" style="${!p.isValid ? 'border-color:#ef4444;border-width:2px' : ''}"><div class="product-header"><span>#${String(p.index).padStart(2, '0')} - ${p.type}</span>${!p.isValid ? '<span style="color:#ef4444">⚠️ INCOMPLET</span>' : ''}</div><div class="product-body"><div class="specs"><table class="spec-table">${r}</table>${nt}</div><div class="visuals">${dr}${im}</div></div></div>`;
    });
    h += '</body></html>'; return h;
};
